filePath:
  recordPathJson_dir: /home/aaa/catkin_qt/src/demo_smarco_robot/etc/recordPath/
  electronicFence_dir: ~
robot:
  floor: 3
  server_port: 6789
  server_addr: 192.168.1.9
  raw_speed: 0.2
  filesDir: /home/aaa/catkin_qt/src/demo_smarco_robot/etc
  id: 230708065
  line_speed: 0.2
ftp:
  port: 32321
  user: myftp
  uploadDir: /upload
  host: 221.231.13.226
  pwd: myftp@2023